### ISSUE TITLE
Code review 2021/06/01

### ISSUE THREAD

**Issue by El-Potato-Slayer** [rahalrazika/Calculator#6]
You were given a task to develop a calculator, but that's not what I see at all. One glance of your code has made me enter a state of impossible existence; I exist, yet I don't; I am everywhere, yet I am nowhere. Everywhere I look, I can see beyond the farthest reaches of our universe, yet at the same time, I can see what exists beyond the Planck length. Yet within this ambiguous existence, I inhabit an infinite amount of multidimensional multiversal matrixes, all of which exist on a 0-dimensional plane. However, I am still able to sift through all of this information and remember that today is the anniversary of when we first joined Microverse. Happy 1 year anniversary :D

This is the inevitable outcome of such perfect code.

2020/06/01 - 2021/06/01

**Comment by rahalrazika** [comment]
Thanks, chad this is the best issue <3

**Comment by anewman15** [comment]
> Thanks, chad this is the best issue <3

No way Raza, this doesn't include me. How mean! I'm downvoting this!
